/*
THIS IS A GENERATED/BUNDLED FILE BY ESBUILD
if you want to view the source, please visit the github repository of this plugin
*/

var __defProp = Object.defineProperty;
var __getOwnPropDesc = Object.getOwnPropertyDescriptor;
var __getOwnPropNames = Object.getOwnPropertyNames;
var __hasOwnProp = Object.prototype.hasOwnProperty;
var __export = (target, all) => {
  for (var name in all)
    __defProp(target, name, { get: all[name], enumerable: true });
};
var __copyProps = (to, from, except, desc) => {
  if (from && typeof from === "object" || typeof from === "function") {
    for (let key of __getOwnPropNames(from))
      if (!__hasOwnProp.call(to, key) && key !== except)
        __defProp(to, key, { get: () => from[key], enumerable: !(desc = __getOwnPropDesc(from, key)) || desc.enumerable });
  }
  return to;
};
var __toCommonJS = (mod) => __copyProps(__defProp({}, "__esModule", { value: true }), mod);

// main.ts
var main_exports = {};
__export(main_exports, {
  default: () => LinkUpdaterPlugin
});
module.exports = __toCommonJS(main_exports);
var import_obsidian = require("obsidian");
var LinkUpdaterPlugin = class extends import_obsidian.Plugin {
  constructor() {
    super(...arguments);
    this.clipboardData = null;
    this.isCutOperation = false;
  }
  async onload() {
    console.log("Link Updater Plugin loaded");
    this.registerDomEvent(document, "cut", this.handleDocumentCut.bind(this), true);
    this.registerDomEvent(document, "copy", this.handleDocumentCopy.bind(this), true);
    this.registerDomEvent(document, "paste", this.handleDocumentPaste.bind(this), true);
    this.addCommand({
      id: "toggle-link-updater",
      name: "Toggle Link Updater",
      callback: () => {
        new import_obsidian.Notice("Link Updater is active");
      }
    });
  }
  handleDocumentCut(evt) {
    const activeView = this.app.workspace.getActiveViewOfType(import_obsidian.MarkdownView);
    if (activeView && activeView.editor) {
      this.isCutOperation = true;
      this.captureSourceContext(activeView.editor);
    }
  }
  handleDocumentCopy(evt) {
    const activeView = this.app.workspace.getActiveViewOfType(import_obsidian.MarkdownView);
    if (activeView && activeView.editor) {
      this.isCutOperation = false;
      this.captureSourceContext(activeView.editor);
    }
  }
  captureSourceContext(editor) {
    const activeView = this.app.workspace.getActiveViewOfType(import_obsidian.MarkdownView);
    if (activeView && activeView.file) {
      const selection = editor.getSelection();
      this.clipboardData = {
        sourceFilePath: activeView.file.path,
        content: selection
      };
    }
  }
  handleDocumentPaste(evt) {
    var _a, _b, _c;
    const targetView = this.app.workspace.getActiveViewOfType(import_obsidian.MarkdownView);
    if (!targetView || !targetView.file || !targetView.editor) {
      return;
    }
    const targetFilePath = targetView.file.path;
    const clipboardText = (_a = evt.clipboardData) == null ? void 0 : _a.getData("text/plain");
    if (!clipboardText) {
      return;
    }
    let sourceFilePath = (_b = this.clipboardData) == null ? void 0 : _b.sourceFilePath;
    if (!sourceFilePath && ((_c = this.clipboardData) == null ? void 0 : _c.content) === clipboardText) {
      sourceFilePath = this.clipboardData.sourceFilePath;
    }
    if (!sourceFilePath) {
      sourceFilePath = this.guessSourceFromContent(clipboardText);
    }
    if (sourceFilePath && sourceFilePath !== targetFilePath) {
      evt.preventDefault();
      const updatedContent = this.updateLinksInContent(
        clipboardText,
        sourceFilePath,
        targetFilePath
      );
      targetView.editor.replaceSelection(updatedContent);
      this.showUpdateNotification();
    }
    this.clipboardData = null;
    this.isCutOperation = false;
  }
  guessSourceFromContent(content) {
    const wikiLinkRegex = /\[\[([^\]#|]+)(?:#[^\]|]*)?(?:\|[^\]]*)?\]\]/g;
    const mdLinkRegex = /\[([^\]]*)\]\(([^)#]+)(?:#[^)]*)?\)/g;
    let match;
    const potentialFiles = /* @__PURE__ */ new Set();
    while ((match = wikiLinkRegex.exec(content)) !== null) {
      const linkPath = match[1].trim();
      this.addPotentialSourceFile(linkPath, potentialFiles);
    }
    while ((match = mdLinkRegex.exec(content)) !== null) {
      const linkPath = match[2].trim();
      this.addPotentialSourceFile(linkPath, potentialFiles);
    }
    return potentialFiles.size === 1 ? Array.from(potentialFiles)[0] : null;
  }
  addPotentialSourceFile(linkPath, potentialFiles) {
    const cleanPath = linkPath.replace(/\.md$/, "");
    const linkedFile = this.app.metadataCache.getFirstLinkpathDest(cleanPath, "");
    if (linkedFile) {
      const allLinks = this.app.metadataCache.resolvedLinks;
      for (const [sourceFile, links] of Object.entries(allLinks)) {
        if (links[linkedFile.path]) {
          potentialFiles.add(sourceFile);
        }
      }
    }
  }
  updateLinksInContent(content, sourceFilePath, targetFilePath) {
    let updatedContent = content;
    updatedContent = updatedContent.replace(
      /(\[\[)([^\]#|]+)(#[^\]|]*)?(\|[^\]]*)?(\]\])/g,
      (match, prefix, linkPath, heading, alias, suffix) => {
        const cleanLinkPath = linkPath.trim();
        const targetFile = this.resolveTargetFile(cleanLinkPath, sourceFilePath);
        if (targetFile) {
          const correctLinkForTarget = this.generateCorrectLink(
            targetFile,
            targetFilePath,
            heading
          );
          const aliasPart = alias || "";
          return `${prefix}${correctLinkForTarget}${aliasPart}${suffix}`;
        }
        return match;
      }
    );
    updatedContent = updatedContent.replace(
      /(\[[^\]]*\]\()([^)#]+)(#[^)]*)?(\))/g,
      (match, prefix, linkPath, heading, suffix) => {
        const cleanLinkPath = linkPath.trim().replace(/\.md$/, "");
        const targetFile = this.resolveTargetFile(cleanLinkPath, sourceFilePath);
        if (targetFile) {
          const correctLinkForTarget = this.generateCorrectMarkdownLink(
            targetFile,
            targetFilePath,
            heading
          );
          return `${prefix}${correctLinkForTarget}${suffix}`;
        }
        return match;
      }
    );
    return updatedContent;
  }
  resolveTargetFile(linkPath, sourceFilePath) {
    const sourceFile = this.app.vault.getFileByPath(sourceFilePath);
    if (!sourceFile) {
      return this.app.metadataCache.getFirstLinkpathDest(linkPath, "");
    }
    return this.app.metadataCache.getFirstLinkpathDest(linkPath, sourceFilePath);
  }
  generateCorrectLink(targetFile, currentFilePath, heading) {
    const currentFile = this.app.vault.getFileByPath(currentFilePath);
    if (!currentFile || !currentFile.parent) {
      return heading ? `${targetFile.basename}${heading}` : targetFile.basename;
    }
    const relativePath = this.getRelativePath(currentFile.parent, targetFile);
    const linkWithoutExt = relativePath.replace(/\.md$/, "");
    return heading ? `${linkWithoutExt}${heading}` : linkWithoutExt;
  }
  generateCorrectMarkdownLink(targetFile, currentFilePath, heading) {
    const currentFile = this.app.vault.getFileByPath(currentFilePath);
    if (!currentFile || !currentFile.parent) {
      return heading ? `${targetFile.name}${heading}` : targetFile.name;
    }
    const relativePath = this.getRelativePath(currentFile.parent, targetFile);
    return heading ? `${relativePath}${heading}` : relativePath;
  }
  getRelativePath(from, to) {
    const fromParts = from.path.split("/").filter((p) => p);
    const toParts = to.path.split("/").filter((p) => p);
    let commonLength = 0;
    while (commonLength < fromParts.length && commonLength < toParts.length && fromParts[commonLength] === toParts[commonLength]) {
      commonLength++;
    }
    const relativeParts = [];
    for (let i = commonLength; i < fromParts.length; i++) {
      relativeParts.push("..");
    }
    for (let i = commonLength; i < toParts.length; i++) {
      relativeParts.push(toParts[i]);
    }
    return relativeParts.join("/");
  }
  showUpdateNotification() {
    new import_obsidian.Notice("Internal links have been automatically updated");
  }
  onunload() {
    console.log("Link Updater Plugin unloaded");
  }
};
