/*
THIS IS A GENERATED/BUNDLED FILE BY ESBUILD
if you want to view the source, please visit the github repository of this plugin
*/

var __defProp = Object.defineProperty;
var __getOwnPropDesc = Object.getOwnPropertyDescriptor;
var __getOwnPropNames = Object.getOwnPropertyNames;
var __hasOwnProp = Object.prototype.hasOwnProperty;
var __export = (target, all) => {
  for (var name in all)
    __defProp(target, name, { get: all[name], enumerable: true });
};
var __copyProps = (to, from, except, desc) => {
  if (from && typeof from === "object" || typeof from === "function") {
    for (let key of __getOwnPropNames(from))
      if (!__hasOwnProp.call(to, key) && key !== except)
        __defProp(to, key, { get: () => from[key], enumerable: !(desc = __getOwnPropDesc(from, key)) || desc.enumerable });
  }
  return to;
};
var __toCommonJS = (mod) => __copyProps(__defProp({}, "__esModule", { value: true }), mod);

// main.ts
var main_exports = {};
__export(main_exports, {
  default: () => LinkUpdaterPlugin
});
module.exports = __toCommonJS(main_exports);
var import_obsidian = require("obsidian");
var LinkUpdaterPlugin = class extends import_obsidian.Plugin {
  constructor() {
    super(...arguments);
    this.clipboardSource = null;
  }
  async onload() {
    console.log("Loading Link Updater plugin");
    this.registerDomEvent(document, "copy", this.handleCopy.bind(this));
    this.registerDomEvent(document, "cut", this.handleCut.bind(this));
    this.registerDomEvent(document, "paste", this.handlePaste.bind(this));
  }
  onunload() {
    console.log("Unloading Link Updater plugin");
  }
  handleCopy(e) {
    this.saveClipboardSource(e);
  }
  handleCut(e) {
    this.saveClipboardSource(e);
  }
  saveClipboardSource(e) {
    const activeView = this.app.workspace.getActiveViewOfType(import_obsidian.MarkdownView);
    if (!activeView)
      return;
    const file = activeView.file;
    if (!file)
      return;
    this.clipboardSource = file.path;
  }
  handlePaste(e) {
    const activeView = this.app.workspace.getActiveViewOfType(import_obsidian.MarkdownView);
    if (!activeView)
      return;
    const targetFile = activeView.file;
    if (!targetFile)
      return;
    const sourcePath = this.clipboardSource;
    if (!sourcePath)
      return;
    if (sourcePath === targetFile.path)
      return;
    e.preventDefault();
    const clipboardData = e.clipboardData;
    if (!clipboardData)
      return;
    let content = clipboardData.getData("text/plain");
    if (!content)
      return;
    const updatedContent = this.updateLinks(content, sourcePath, targetFile);
    activeView.editor.replaceSelection(updatedContent);
    new import_obsidian.Notice("Links updated to match new file location");
    this.clipboardSource = null;
  }
  updateLinks(content, sourcePath, targetFile) {
    const wikilinkRegex = /\[\[(.*?)(\|.*?)?\]\]/g;
    const mdlinkRegex = /\[([^\]]*)\]\(([^)]+)\)/g;
    let updatedContent = content;
    updatedContent = updatedContent.replace(wikilinkRegex, (match, link, alias) => {
      const newLink = this.resolveLink(link, sourcePath, targetFile);
      return `[[${newLink}${alias || ""}]]`;
    });
    updatedContent = updatedContent.replace(mdlinkRegex, (match, text, url) => {
      if (url.startsWith("http://") || url.startsWith("https://")) {
        return match;
      }
      const newUrl = this.resolveLink(url, sourcePath, targetFile);
      return `[${text}](${newUrl})`;
    });
    return updatedContent;
  }
  resolveLink(link, sourcePath, targetFile) {
    link = link.trim();
    const sourceFile = this.app.vault.getAbstractFileByPath(sourcePath);
    if (!(sourceFile instanceof import_obsidian.TFile))
      return link;
    const sourceDir = sourceFile.parent;
    const targetDir = targetFile.parent;
    let linkedFile = this.app.metadataCache.getFirstLinkpathDest(link, sourcePath);
    if (!linkedFile) {
      linkedFile = this.findFileByFullPath(link);
    }
    if (!linkedFile) {
      return link;
    }
    const relativePath = this.getRelativePath(targetDir, linkedFile);
    return relativePath;
  }
  findFileByFullPath(path) {
    const file = this.app.vault.getAbstractFileByPath(path);
    if (file instanceof import_obsidian.TFile)
      return file;
    const allFiles = this.app.vault.getMarkdownFiles();
    for (const f of allFiles) {
      if (f.path === path || f.name === path) {
        return f;
      }
    }
    return null;
  }
  getRelativePath(fromDir, toFile) {
    var _a;
    if (!fromDir)
      return toFile.path;
    const fromPath = fromDir.path;
    const toPath = toFile.path;
    if (fromPath === ((_a = toFile.parent) == null ? void 0 : _a.path)) {
      return toFile.name;
    }
    const fromParts = fromPath.split("/").filter(Boolean);
    const toParts = toPath.split("/").filter(Boolean);
    let commonDepth = 0;
    while (commonDepth < fromParts.length && commonDepth < toParts.length && fromParts[commonDepth] === toParts[commonDepth]) {
      commonDepth++;
    }
    const upLevels = fromParts.length - commonDepth;
    const relativeParts = [];
    for (let i = 0; i < upLevels; i++) {
      relativeParts.push("..");
    }
    for (let i = commonDepth; i < toParts.length; i++) {
      relativeParts.push(toParts[i]);
    }
    return relativeParts.join("/");
  }
};
